/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as UserRouteImport } from './routes/user'
import { Route as KatalogSkillIdRouteImport } from './routes/katalog_.$skillId'
import { Route as KatalogNewRouteImport } from './routes/katalog_.new'
import { Route as KatalogSkillIdEditRouteImport } from './routes/katalog_.$skillId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogSkillIdRoute = KatalogSkillIdRouteImport.update({
  id: '/katalog_/$skillId',
  path: '/katalog/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogNewRoute = KatalogNewRouteImport.update({
  id: '/katalog_/new',
  path: '/katalog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogSkillIdEditRoute = KatalogSkillIdEditRouteImport.update({
  id: '/katalog_/$skillId_/edit',
  path: '/katalog/$skillId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/katalog': typeof KatalogRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/testimoni': typeof TestimoniRoute
  '/user': typeof UserRoute
  '/katalog/$skillId': typeof KatalogSkillIdRoute
  '/katalog/new': typeof KatalogNewRoute
  '/katalog/$skillId/edit': typeof KatalogSkillIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/katalog': typeof KatalogRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/testimoni': typeof TestimoniRoute
  '/user': typeof UserRoute
  '/katalog/$skillId': typeof KatalogSkillIdRoute
  '/katalog/new': typeof KatalogNewRoute
  '/katalog/$skillId/edit': typeof KatalogSkillIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/katalog': typeof KatalogRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/testimoni': typeof TestimoniRoute
  '/user': typeof UserRoute
  '/katalog_/$skillId': typeof KatalogSkillIdRoute
  '/katalog_/new': typeof KatalogNewRoute
  '/katalog_/$skillId_/edit': typeof KatalogSkillIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/feedback'
    | '/katalog'
    | '/leaderboard'
    | '/login'
    | '/plan'
    | '/testimoni'
    | '/user'
    | '/katalog/$skillId'
    | '/katalog/new'
    | '/katalog/$skillId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/feedback'
    | '/katalog'
    | '/leaderboard'
    | '/login'
    | '/plan'
    | '/testimoni'
    | '/user'
    | '/katalog/$skillId'
    | '/katalog/new'
    | '/katalog/$skillId/edit'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/feedback'
    | '/katalog'
    | '/leaderboard'
    | '/login'
    | '/plan'
    | '/testimoni'
    | '/user'
    | '/katalog_/$skillId'
    | '/katalog_/new'
    | '/katalog_/$skillId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FeedbackRoute: typeof FeedbackRoute
  KatalogRoute: typeof KatalogRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  TestimoniRoute: typeof TestimoniRoute
  UserRoute: typeof UserRoute
  KatalogSkillIdRoute: typeof KatalogSkillIdRoute
  KatalogNewRoute: typeof KatalogNewRoute
  KatalogSkillIdEditRoute: typeof KatalogSkillIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog_/$skillId': {
      id: '/katalog_/$skillId'
      path: '/katalog/$skillId'
      fullPath: '/katalog/$skillId'
      preLoaderRoute: typeof KatalogSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog_/new': {
      id: '/katalog_/new'
      path: '/katalog/new'
      fullPath: '/katalog/new'
      preLoaderRoute: typeof KatalogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog_/$skillId_/edit': {
      id: '/katalog_/$skillId_/edit'
      path: '/katalog/$skillId/edit'
      fullPath: '/katalog/$skillId/edit'
      preLoaderRoute: typeof KatalogSkillIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FeedbackRoute: FeedbackRoute,
  KatalogRoute: KatalogRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  TestimoniRoute: TestimoniRoute,
  UserRoute: UserRoute,
  KatalogSkillIdRoute: KatalogSkillIdRoute,
  KatalogNewRoute: KatalogNewRoute,
  KatalogSkillIdEditRoute: KatalogSkillIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
